### ISSUE TITLE
Using regexp parser leads to error "Cannot read properties of undefined" 

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#254] opened 2022-11-18 18:15 UTC
I'm fail to get working example with regexp parser. UPlease point me, what did I miss?

Simplified example

### 1. Ok query
```
{namespace="argocd"} | line_format "1x" 
```
shows
1x
1x
1x

### 2. Not ok query
```
{namespace="argocd"} | line_format "1x" | regexp `(?<number>\d)x`
```
shows "No data"

qryn report errors in logs:
```
{"level":30,"time":1668794859649,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17g","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1668794857726000000&limit=1000&query=%7Bnamespace%3D%22argocd%22%7D+%7C+line_format+%221x%22+%7C+regexp+%60%28%3F%3Cnumber%3E%5Cd%29x%60&start=1668708457726000000&step=60000ms","hostname":"cloki1.xxx.local:3100","remoteAddress":"x.x.x.x","remotePort":59412},"msg":"incoming request"}
{"level":50,"time":1668794859697,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17g","err":"Cannot read properties of undefined (reading 'withs')\nTypeError: Cannot read properties of undefined (reading 'withs')\n    at Select._with (/app/node_modules/@cloki/clickhouse-sql/dist/index.js:899:55)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:147:14)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"Cannot read properties of undefined (reading 'withs')"}
{"level":30,"time":1668794859698,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17g","res":{"statusCode":200},"responseTime":48.483317375183105,"msg":"request completed"}
{"level":30,"time":1668794859698,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17h","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1668794857726000000&limit=1000&query=sum+by+%28level%29+%28count_over_time%28%7Bnamespace%3D%22argocd%22%7D+%7C+line_format+%221x%22+%7C+regexp+%60%28%3F%3Cnumber%3E%5Cd%29x%60%5B1m%5D%29%29&start=1668708457726000000&step=60000ms","hostname":"cloki1.xxx.local:3100","remoteAddress":"x.x.x.x","remotePort":59434},"msg":"incoming request"}
{"level":50,"time":1668794859760,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17h","err":"Cannot read properties of undefined (reading 'ctx')\nTypeError: Cannot read properties of undefined (reading 'ctx')\n    at genericRate (/app/parser/registry/log_range_aggregation_registry/log_range_agg_reg.js:27:9)\n    at Object.count_over_time (/app/parser/registry/log_range_aggregation_registry/index.js:33:12)\n    at Object.module.exports.transpileLogRangeAggregation (/app/parser/transpiler.js:310:82)\n    at Object.module.exports.transpileAggregationOperator (/app/parser/transpiler.js:294:28)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:133:30)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"Cannot read properties of undefined (reading 'ctx')"}
{"level":30,"time":1668794859761,"pid":20,"hostname":"55bf8f6368f6","name":"qryn","reqId":"req-17h","res":{"statusCode":200},"responseTime":62.40519428253174,"msg":"request completed"}
```
I have tried other options but without any success.

docker-qryn v2.1.46
grafana 9.2.5
clickhouse 21.8.15.7

**Comment by lmangani** [comment] 2022-11-18 21:16
Thanks for the report @MalKeshar 
The regex stage before the line_format should be working fine but clearly the opposite does not. We'll check and replicate.

**Comment by Dletta** [comment] 2022-11-18 21:23
@MalKeshar 
Indeed this does work in Loki vs qryn and we will put this on the to do list.

**Comment by akvlad** [comment] 2022-11-21 14:09
@MalKeshar the issue is fixed in https://github.com/metrico/qryn/pull/257 . 
The branch will be merged into master after some extra tests.
Anyway, autotests are successful.  Feel free to check.

**Comment by MalKeshar** [comment] 2022-11-23 17:21
Thank you!

**Comment by akvlad** [comment] 2022-11-23 19:40
The branch is merged.

**Closed by akvlad** 2022-11-23 19:40 UTC
Labels: bug, help wanted
