### ISSUE TITLE
Request error and cpu usage

### ISSUE THREAD

**Issue by R-omk** [metrico/qryn#253] opened 2022-11-18 11:25 UTC
During the request (can see the log below), it got stuck for 20 seconds while consuming 100% of the processor time, after which the error information appeared in the logs and no requests were made to the clickhouse storage.

qryn log:

```
2022-11-18T11:14:40.482724305Z {"level":30,"time":1668770080482,"pid":19,"hostname":"qryn-direct-reader-5f958dd46f-jx42w","name":"qryn","reqId":"req-7c","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1668770080333000000&limit=1000&query=sum%28count_over_time%28%7Bnamespace%3D~%22staging%22%2C+pod%3D~%22stg-core-nginx-6bb569dc78%22%2C+stream%3D%22stdout%22%2C+container%3D%22nginx%22%7D+%7C%3D+%60wee%60++%7C++json+request_uri%3D%22message.request_uri%22+%7C+unwrap+%5B5m%5D%29%29&start=1668768280333000000&step=1000ms","hostname":"qryn-direct-reader.logging.svc:8080","remoteAddress":"10.233.123.184","remotePort":39928},"msg":"incoming request"}
2022-11-18T11:14:59.406183477Z Couldn't execute script:
2022-11-18T11:14:59.407188789Z Expected [ or 'WSP' ] @1:94 encountered ' co'.
2022-11-18T11:14:59.407231644Z sum(count_over_time({namespace=~"staging", pod=~"stg-core-nginx-6bb569dc78", stream="stdout", container="nginx"} |= `wee`  |  json request_uri="message.request_uri" | unwrap [5m]))
2022-11-18T11:14:59.407794624Z {"level":50,"time":1668770099407,"pid":19,"hostname":"qryn-direct-reader-5f958dd46f-jx42w","name":"qryn","reqId":"req-7c","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at Object.module.exports.transpile (/app/parser/transpiler.js:90:28)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"Cannot read properties of null (reading 'rootToken')"}
2022-11-18T11:14:59.407969807Z {"level":30,"time":1668770099407,"pid":19,"hostname":"qryn-direct-reader-5f958dd46f-jx42w","name":"qryn","reqId":"req-7c","res":{"statusCode":200},"responseTime":18925.234073638916,"msg":"request completed"}


```

version: docker.io/qxip/qryn:v2.1.45
env LINE_FMT=go_native

**Comment by akvlad** [comment] 2022-11-18 11:42
`sum() `I   believe is not supported.
`sum() by (...) ` - is a correct request.
if you want `sum()` then you can just omit sum() because it's a sum of 1 element.

100% cpu and delay is I think because of internal implementation of parser. Well, maybe the BNF part is not that flawless.

**Comment by R-omk** [comment] 2022-11-18 12:09
This construction `sum(count_over_time(` works,  but it it works till I add `unwrap`

no request works for me if it contains `unwrap` word

**Comment by akvlad** [comment] 2022-11-18 12:21
let's check the documentation. There are two types of operations:
- https://github.com/metrico/qryn/wiki/LogQL-Supported-Queries#log-range-aggregations : these **don't** work with unwrap.
- https://github.com/metrico/qryn/wiki/LogQL-Supported-Queries#unwrap-expression : these work **only** with unwrap
- https://github.com/metrico/qryn/wiki/LogQL-Supported-Queries#aggregation-operators : these work with **both** as these are the second level of aggregation.

so if you try `| unwrap` , please check something like `avg_over_time(.... | unwrap "...." [....])`

**Comment by R-omk** [comment] 2022-11-18 12:37
when I execute the expression described in the wiki, I get the following result


```
{"level":50,"time":1668774793265,"pid":19,"hostname":"qryn-direct-reader-5f958dd46f-6st4m","name":"qryn","reqId":"req-3i","err":"Cannot read properties of undefined (reading 'split')\nTypeError: Cannot read properties of undefined (reading 'split')\n    at Term.toString (/app/node_modules/@cloki/clickhouse-sql/dist/index.js:476:29)\n    at /app/node_modules/@cloki/clickhouse-sql/dist/index.js:1147:62\n    at Array.map (<anonymous>)\n    at Select.toString (/app/node_modules/@cloki/clickhouse-sql/dist/index.js:1146:40)\n    at With.toString (/app/node_modules/@cloki/clickhouse-sql/dist/index.js:707:63)\n    at Array.join (<anonymous>)\n    at Select.toString (/app/node_modules/@cloki/clickhouse-sql/dist/index.js:1140:40)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:167:22)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)","msg":"Cannot read properties of undefined (reading 'split')"}
{"level":30,"time":1668774793266,"pid":19,"hostname":"qryn-direct-reader-5f958dd46f-6st4m","name":"qryn","reqId":"req-3i","res":{"statusCode":200},"responseTime":111.36630630493164,"msg":"request completed"}

```

`rate({label1="val1"}|unwrap int_valued_label [1s]) by (another_label)`

**Comment by akvlad** [comment] 2022-11-18 12:59
Seems like a bug.
Feature definitely tested today is something like `rate({label1="val1"} | regexp "^(?<nothing>.)" | unwrap int_valued_label [1s]) by (another_label)` . please use this for now. I'll check why the described case doesn't work.

Thanks for the report.

**Comment by R-omk** [comment] 2022-11-18 13:06
Here's another example,

successfully completed
`sum(count_over_time({pod=~"stg-core-nginx-6bb569dc78"}   |   json request_uri="message.request_uri"   [1m])) by (request_uri )`

add  ` | request_uri!~'noti'`

`sum(count_over_time({pod=~"stg-core-nginx-6bb569dc78"}   |   json request_uri="message.request_uri"  | request_uri!~'noti'  [1m])) by (request_uri ) `

as a result:
stuck and fail with error posted in message of the issue `Cannot read properties of null (reading 'rootToken')`

**Comment by R-omk** [comment] 2022-11-18 13:24
I think I'm trying to find a problem where there isn't one)

in any case, qryn responds with status 200 even if there are errors, this is strange...  and lock js event loop for 19s

**Comment by akvlad** [comment] 2022-11-18 13:33
There was an issue with non-200 responses and logs push clients. Maybe we need 400 or 500 responses for reader routes.
I'll check.

**Comment by akvlad** [comment] 2022-11-18 13:42
- [ ] check a problematic request: 
```
sum(count_over_time({namespace=~"staging", pod=~"stg-core-nginx-6bb569dc78", stream="stdout", container="nginx"} |= `wee`  | json request_uri="message.request_uri" | unwrap [5m]))
```
gets 19s to be parsed
- [ ] `rate({label="val"} | unwrap b [1s])` requests fail
- [ ] response with a legit error code if a request is erroneous

Will work on it.

**Comment by akvlad** [comment] 2022-11-21 13:18
@R-omk I have the issues fixed in a separate branch https://github.com/metrico/qryn/tree/issue_253 . We need to test it more closely because I changed some core functionality. But the autotests passed successfully. 
Please check.

**Comment by R-omk** [comment] 2022-11-22 08:16
version:  beta ([51fb31a](https://github.com/metrico/qryn/commit/51fb31a9003aaddb74f069f16b73417d4bf2e8f0))


```
2022-11-22T08:07:44.225620747Z {"level":30,"time":1669104464225,"pid":19,"hostname":"qryn-direct-reader-5c9ddfd68b-lvs9k","name":"qryn","reqId":"req-1c","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1669104464109000000&limit=1000&query=sum%28count_over_time%28%7Blabel%3D%22val%22%7D++%7C+json+f1%3D%22message.f1%22+%7C+unwrap+%5B5m%5D%29%29&start=1669104164109000000&step=100ms","hostname":"qryn-direct-reader.logging.svc:8080","remoteAddress":"10.233.123.184","remotePort":55186},"msg":"incoming request"}
2022-11-22T08:07:44.230635747Z Couldn't execute script:
2022-11-22T08:07:44.230679904Z Expected [ or 'SYNTAX' ] @1:0 encountered 'sum(c'.
2022-11-22T08:07:44.230688992Z sum(count_over_time({label="val"}  | json f1="message.f1" | unwrap [5m]))
2022-11-22T08:07:44.230970837Z {"level":50,"time":1669104464230,"pid":19,"hostname":"qryn-direct-reader-5c9ddfd68b-lvs9k","name":"qryn","reqId":"req-1c","err":"invalid request\nBad Request: invalid request\n    at Object.module.exports.transpile (/app/parser/transpiler.js:92:11)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:223:29)\n    at Object.handler (/app/lib/handlers/query_range.js:41:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"invalid request"}
2022-11-22T08:07:44.231326015Z {"level":30,"time":1669104464231,"pid":19,"hostname":"qryn-direct-reader-5c9ddfd68b-lvs9k","name":"qryn","reqId":"req-1c","res":{"statusCode":400},"responseTime":5.7067365646362305,"msg":"request completed"}

```

--

**Comment by akvlad** [comment] 2022-11-22 08:41
@R-omk I see no issues in the logs. Can you explain a bit?

**Comment by R-omk** [comment] 2022-11-22 08:47
my bad. it's not a valid request, you already explain that.

**Comment by akvlad** [comment] 2022-11-22 08:49
Yeah `|unwrap` needs a label name after.  As you see, it was processed in 0.005s instead of 19s previously.

**Comment by R-omk** [comment] 2022-11-22 09:09
It looks like all the points listed earlier have been resolved.

**Comment by akvlad** [comment] 2022-11-22 09:26
@R-omk Great to hear. Please use the beta branch and notify us about any regression bugs you observe. 
I'll merge the branch in a couple of days.

**Comment by akvlad** [comment] 2022-11-23 19:39
Merged. 
If no new questions, I close the issue.

**Closed by akvlad** 2022-11-23 19:39 UTC
