### ISSUE TITLE
Requsets to qryn api fails sometimes!

### ISSUE THREAD

**Issue by MohammadrezaNasrabadi** [metrico/qryn#255] opened 2022-11-19 13:12 UTC
I have a monitoring stack composed of `promtail` , `grafana`, `qryn` and `clickhouse` services. `promtail` applies labels and sends logs toward `qryn` and `qryn` stores logs on `clickhouse`.

If a `qryn` API request is sent, qryn behaves strangely! Sometimes these queries will be responded successfully, like below:

![image](https://user-images.githubusercontent.com/77168970/202852185-7d2772ab-ec3d-44f6-bb75-1fcff7915e6e.png)

And it's return code thrown on `qryn` logs is 200:

```

 {"level":30,"time":1668862103392,"pid":21,"hostname":"monitoring","name":"qryn","reqId":"req-qa","res":{"statusCode":200},"responseTime":3.4170875549316406,"msg":"request completed"}

```

But sometimes (this behavior happens a lot) my requests fails:

![image](https://user-images.githubusercontent.com/77168970/202852409-12ac84c5-1de1-4791-a6a3-29e56a8448a5.png)

And the related `qryn` log is:

```

{"level":50,"time":1668862117855,"pid":21,"hostname":"monitoring","name":"qryn","reqId":"req-qj","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}

```

**Comment by lmangani** [comment] 2022-11-19 14:27
Thanks for your report @MohammadrezaNasrabadi 
Could you confirm if you see any errors while inserting data, or only when running a query?

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-19 14:45
> Thanks for your report @MohammadrezaNasrabadi Could you confirm if you see any errors while inserting data, or only when running a query?

I checked POST method logs on `qryn` and I haven't seen any error on inserting data. All of status codes are 204

**Comment by lmangani** [comment] 2022-11-19 14:48
Thanks for the update. How about ClickHouse? Do you see any errors while inserting and/or running the problem queries? 
Could you also add any messages from the qryn logs preceding the 500 error?

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-19 14:55
Below are different types of 500 error:

```
{"level":50,"time":1668869289495,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-5rs","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}

```
```
{"level":50,"time":1668869284932,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-5rl","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}

```

```
{"level":50,"time":1668869466009,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-5w9","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}

```

```

{"level":50,"time":1668869562667,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-5yu","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}


```




How should I make ensure about clickhouse health functionality? I don't see any error log on clickhouse side.

**Comment by lmangani** [comment] 2022-11-19 15:00
Thanks, this helps. We'll try to replicate this and as soon as we do, a fix will be available.

No errors mean no issues, so the ClickHouse side should only be monitored in terms of load/IO performance.

**Comment by lmangani** [comment] 2022-11-19 15:02
> Below are some 500 errors:

Are you positive there are no other related log messages before the 500?

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-19 15:08
Thanks a lot. These are logs related to my queries:

The below logs are related to the query proceeded from grafana:

```
{"level":30,"time":1668869922895,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-687","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1668869922571000000&limit=1000&query=%7Bappname%3D%22sudo%22%7D&start=1668859122571000000&step=5000ms","hostname":"qryn:3100","remoteAddress":"127.0.0.1","remotePort":44224},"msg":"incoming request"}
{"level":30,"time":1668869922902,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-688","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1668869922571000000&limit=1000&query=sum+by+%28level%29+%28count_over_time%28%7Bappname%3D%22sudo%22%7D%5B1m%5D%29%29&start=1668859122571000000&step=60000ms","hostname":"qryn:3100","remoteAddress":"127.0.0.1","remotePort":44240},"msg":"incoming request"}
{"level":30,"time":1668869922911,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-689","req":{"method":"GET","url":"/loki/api/v1/labels?start=1668859122649000000&end=1668869922649000000","hostname":"qryn:3100","remoteAddress":"127.0.0.1","remotePort":44250},"msg":"incoming request"}
{"level":30,"time":1668869922926,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-689","res":{"statusCode":200},"responseTime":14.67095947265625,"msg":"request completed"}
{"level":50,"time":1668869923655,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-688","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}
{"level":30,"time":1668869923656,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-688","res":{"statusCode":200},"responseTime":753.7646312713623,"msg":"request completed"}
{"level":50,"time":1668869923678,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-687","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}
{"level":30,"time":1668869923679,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-687","res":{"statusCode":200},"responseTime":783.7891244888306,"msg":"request completed"}
```

Also below is error response when our services had requested the query:

```
{"level":30,"time":1668870396373,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-6k7","req":{"method":"GET","url":"/loki/api/v1/query_range?start=0&direction=backward&limit=20&query=%7Blevel%3D~%22NOTICE%7Cnotice%22,uid%3D%2263b34bc3-058d-4311-ba0d-66b457572b2f%22,access_level%3D~%22admin%7Ccustomer%22,appname%3D~%22APP1%7CAPP2%7CAPP3%7CAPP4%22%7D&end=1667999353421209200","hostname":"192.168.30.1:3100","remoteAddress":"10.0.2.100","remotePort":39694},"msg":"incoming request"}
{"level":50,"time":1668870396821,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-6k7","err":"Error: Request failed with status code 500\nResponse: [500] [object Object]\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/axios/lib/adapters/http.js:238:9)\n    at RedirectableRequest.emit (events.js:400:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:426:10)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:57:10)\n    at Object.onceWrapper (events.js:520:26)\n    at ClientRequest.emit (events.js:400:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)","msg":"Request failed with status code 500"}
{"level":30,"time":1668870396821,"pid":21,"hostname":"zmon","name":"qryn","reqId":"req-6k7","res":{"statusCode":200},"responseTime":447.91561698913574,"msg":"request completed"}
```

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-19 21:45
I observed from logs that every logs with the same `reqId` value have a status code log equal to 200, even if the log was related to an error response.




![image](https://user-images.githubusercontent.com/77168970/202872636-cccb8e9b-489e-49f0-bc2c-e11ae4e9d464.png)


![image](https://user-images.githubusercontent.com/77168970/202872703-134c12b2-b99d-4cc8-bafa-29608a8d1423.png)

**Comment by akvlad** [comment] 2022-11-21 15:36
Hello @MohammadrezaNasrabadi .
The log reports were appended with some extra error information.
But now all the alterations are in the https://github.com/metrico/qryn/tree/beta branch due to some extra testing needs. Please check your setup with the branch version.

Also please send us some statistics of your qryn database:
`SELECT count(DISTINCT fingerprint) FROM time_series`
`SELECT count(1) FROM samples_v3`
We would like to see your stored amounts of data.

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-21 22:28
Hi @akvlad .
Thanks for your support.

Below are amount of data stored on DB:

![image](https://user-images.githubusercontent.com/77168970/203170550-eb04d7ee-e99e-4b44-848d-91c1afc88d8d.png)

**Comment by akvlad** [comment] 2022-11-22 09:05
3M fingerprints... Well, I don't advice to have more than 10M. 
But please consider reducing cardinality to at least several 100K. High cardinality of key-value sets may cause out-of-memory errors.

Please update to beta branch or please wait until we merge it and let's see the real error returned by clickhouse.

**Comment by akvlad** [comment] 2022-11-23 19:41
The beta branch is merged. Please update and provide the full error log of an unsuccessful request.

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-26 09:44
Thanks a lot, and I apologize for responding late.

I update `qryn`  image to the latest version and there is a real log that `clickhouse` passes to `qryn`. the failed request has been sent from garafana client.


![image](https://user-images.githubusercontent.com/77168970/204082301-a4207c51-edf2-429b-a061-57b9d1b3d156.png)


Actually, We need to limit the amount of `clickhouse` memory usage. What do you recommend for managing clickhouse memory usage without any failure in incoming requests?

**Comment by lmangani** [comment] 2022-11-26 19:23
> Actually, We need to limit the amount of `clickhouse` memory usage. What do you recommend for managing clickhouse memory usage without any failure in incoming requests?

The memory requirements will be directly proportional to the desired/required complexity of your queries. In order to even start to understand what is happening we need more details. How much memory is allocated to qryn and ClickHouse server?

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-27 08:20
We have limited ClickHouse to use 4GB memory and  2 threads.

![image](https://user-images.githubusercontent.com/77168970/204125649-c7956566-0407-4c87-a58a-f891d71551ed.png)

**Comment by lmangani** [comment] 2022-11-27 12:17
High cardinality seems to be the only issue in this equation. 
You should either try to reduce the amount of fingerprints, or allocate more memory, or both.

**Comment by MohammadrezaNasrabadi** [comment] 2022-11-27 13:28
> High cardinality seems to be the only issue in this equation. You should either try to reduce the amount of fingerprints, allocate more memory, or both.

Yes, it makes sense, we decide to reduce the number of received logs via qryn.

Thanks a lot for your amazing support.

**Closed** 2022-11-27 14:30 UTC
Labels: question

**Comment by lmangani** [comment] 2022-11-27 14:31
> Yes, it makes sense, we decide to reduce the number of received logs via qryn.

Mind you do not need to reduce the amount of logs - you can have as many as you want - the issue is just with the amount of labels. So if you reduce the labels you are attaching to logs, the memory requirements should significantly drop.

> Thanks a lot for your amazing support.

You are most welcome! Thanks for the feedback!
